using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using MyNamespace;

namespace MyNamespace
{
    [TestFixture]
    public class FooClassTests
    {
        [Test]
        public void MyPublicMethodTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}